# Generated by Django 4.1.3 on 2023-03-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=83, primary_key=True, serialize=False),
        ),
    ]
